url: http://alicia.y.eduramirez.com/
baseurl: ''

# Site settings
title: "#ramplan2020"
email: edu.rh90@gmail.com
description: "Alicia Planas y Edu Ramírez se casan en Barcelona y Talca el 2020"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/aliciaplanas

# Build settings
markdown: kramdown
permalink: pretty
